### ISSUE TITLE
The error in the Trade method

### ISSUE THREAD

**Issue by hazratgs** [SteleA/btc-e.com-API-wrapper#1]
Hello friend, I really liked your project btc-e.com-API-wrapper, it's the only one that works with btc-e api v3.
But there are some mistakes in it, in particular, in the Trade method, not the right parameters because of what it does not work, as well as I live in Russia and we have some providers blocked by btc-e.com
From which we use the mirror btc-e.nz. Add me to the contributors, and see the edits in my [fork](https://github.com/hazratgs/btc-e-v3)

It is necessary to replace in the method trade:
` return this.makeTradeApiRequest({ method: 'ActiveOrders', pair });`
on
`return this.makeTradeApiRequest({ method: 'Trade', pair, type, rate, amount })`

**Comment by SteleA** [comment]
Hi friend. 

Thanks for noticing my mistake. I have added a mirror option when initiating the constructor. As thanks I added you to the read me.

Happy coding
