### ISSUE TITLE
For public api, there is not parameter limit

### ISSUE THREAD

**Issue by hazratgs** [SteleA/btc-e.com-API-wrapper#2]
Hi, please add the limit parameter for the public api:
`trades(pair, limit)`
and return trades
`return this.makePublicApiRequest({method: 'trades', pair: pair, limit: limit});`
and 
`makePublicApiRequest({ pair, method, limit = 150 }) {`
`const url = '${this.BTC_E_PUBLIC_API}${method}/${pair}?limit=${limit}';`

**Comment by SteleA** [comment]
Done
